# GENERAL_CONSTANTS
MAX_FITNESS_EVALS = -1
MAX_POPULATION_SIZE = -1

SOLUTION_FILE = "solution.csv"

# LOCAL SEARCH CONSTANTS
MAX_TABU_LIST_SIZE = 1000
MAX_ITERATIONS_NUM = 10000

# GA_CONSTANTS
K_GLOBAL = 5
EPSILON = 0.1
N_ch = 5
R_stop = 1500
N_close = 10
